[package]
name = "seal-handshake"
version = "0.1.0"
edition = "2024"

[dependencies]
seal-flow = { path = "../seal-flow", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0.10"
sha2 = "0.10.7"